return{
  "airwolf11250",
  "TheAlexFax67",
  "NinjahExpert",
  "Marshmellogamingz149",
  "Op_Destroyer14",
  "tuva132446", 
  "adris986", 
  "SleepSanGreat", 
  "Tobisanik", 
  "boikatop008", 
  "Duezos", 
  "susl11kk", 
  "JSJSJAJAJAJ",
  "Suslirito",
  "shinobi_apol",
  "GGoodGame"
  "GLPSQUIDY2"
  "MansukhSandhu"
  "Nanni_THEcow"
}
